stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - ls
    - cd LF8
    - mvn -Dmaven.test.skip=true package
  artifacts:
    paths:
        - *

unit-test-job:
  stage: test
  script:
    - mvn test

deploy-job:      
  stage: deploy
  script:
    - echo "Deploying application..."
  only:
    - main