stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - ls
    - cd LF8
    - mvn package

unit-test-job:
  stage: test
  script:
    - mvn test

deploy-job:      
  stage: deploy
  script:
    - echo "Deploying application..."
  only:
    - main