stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - ls
    - touch dummyFile.txt
    - echo "$Sender" >> dummyFile.txt
    - echo "$Passwort" >> dummyFile.txt
    - cat dummyFile.txt
    - cd LF8
    - mvn -Dmaven.test.skip=true package
  artifacts:
    paths:
        - LF8

unit-test-job:
  stage: test
  script:
    - top
    - cd LF8
    - mvn test

deploy-job:      
  stage: deploy
  script:
    - echo "Deploying application..."
  only:
    - main