CREATE TABLE IF NOT EXISTS RAMUSAGE (
    Usage DECIMAL(5,2),
    Date DATETIME NOT NULL,
    TimeInString VARCHAR(23),
    PRIMARY KEY (Date)
);
CREATE TABLE IF NOT EXISTS CPUUSAGE (
    Usage DECIMAL(5,2),
    Date DATETIME NOT NULL,
    TimeInString VARCHAR(23),
    PRIMARY KEY (Date)
);